name: cv
description: Content Values map helpers. Define objects that can be converted to/from maps.
version: 0.2.16+2
homepage: https://github.com/tekartik/cv.dart/tree/main/packages/cv

topics:
  - json

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: '>=1.0.0 <3.0.0'
  meta: '>=1.3.0 <3.0.0'

dev_dependencies:
  test: '>=1.16.0'
  lints: '>=2.1.1'
