name: cv_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: ^3.9.0

dependencies:
  process_run: '>=0.10.0'

dev_dependencies:
  path:
  test: ">=1.26.3"
  dev_build: '>=0.15.5-1'
  lints: '>=2.1.1'
dependency_overrides:
  cv:
    path: ../packages/cv
