name: cv_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  process_run: '>=0.10.0'

dev_dependencies:
  path:
  test: '>=1.0.0'
  dev_test: '>=0.15.5-1'
  lints: '>=2.1.1'
dependency_overrides:
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart
